version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: "space-nginx"
    build:
      context: "."
    ports:
      - "80:80"
      - "443:443"
    networks:
      - spaceify
networks:
  spaceify:
    external:
      name: spaceify
